# Generated by Django 6.0.1 on 2026-01-26 06:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('max_users', models.IntegerField(default=1, help_text='Maximum allowed users in Odoo')),
                ('storage_limit_gb', models.IntegerField(default=10, help_text='Maximum storage in GB')),
                ('allowed_modules', models.JSONField(default=list, help_text='List of Technical Names of allowed modules')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('EXPIRED', 'Expired')], default='ACTIVE', max_length=20)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='saas_core.client')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='saas_core.plan')),
            ],
        ),
        migrations.CreateModel(
            name='OdooInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Instance identifier (e.g. client1)', max_length=100, unique=True)),
                ('db_name', models.CharField(max_length=100)),
                ('db_password', models.CharField(blank=True, max_length=100)),
                ('admin_password', models.CharField(blank=True, max_length=100)),
                ('domain', models.CharField(max_length=255, unique=True)),
                ('port', models.IntegerField(help_text='Assigned internal port', unique=True)),
                ('status', models.CharField(choices=[('CREATED', 'Created - Pending Deployment'), ('RUNNING', 'Running'), ('STOPPED', 'Stopped'), ('ERROR', 'Error')], default='CREATED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='saas_core.client')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instance', to='saas_core.subscription')),
            ],
        ),
    ]
